# Generated by Django 4.1.10 on 2023-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericstatement',
            name='head_statement',
            field=models.BooleanField(default=True),
        ),
    ]
