# Generated by Django 4.1.10 on 2023-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0002_genericstatement_head_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualobject',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='family',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='genericevent',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='genericstatement',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupofpersons',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physicalobject',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='search_notes',
            field=models.TextField(blank=True),
        ),
    ]
