# Generated by Django 4.1.10 on 2023-07-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0005_communicateswith'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicateswith',
            name='method',
            field=models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('written', 'Written')], max_length=50),
        ),
    ]
