# Generated by Django 4.1.10 on 2023-07-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0007_remove_conceptualobject_search_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptualobject',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='genericevent',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='genericstatement',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='groupofpersons',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='physicalobject',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='schuch_index_id',
            new_name='schuh_index_id',
        ),
    ]
