# Generated by Django 4.1.10 on 2023-07-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0008_rename_schuch_index_id_conceptualobject_schuh_index_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arms',
            fields=[
                ('physicalobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.physicalobject')),
                ('arms_type', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.physicalobject',),
        ),
        migrations.CreateModel(
            name='DecorationOfObject',
            fields=[
                ('creationact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.creationact')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.creationact',),
        ),
        migrations.CreateModel(
            name='Festivity',
            fields=[
                ('genericevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.genericevent',),
        ),
        migrations.CreateModel(
            name='GiftGiving',
            fields=[
                ('ownershiptransfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.ownershiptransfer')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.ownershiptransfer',),
        ),
        migrations.CreateModel(
            name='MilitaryCampaign',
            fields=[
                ('genericevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.genericevent',),
        ),
        migrations.CreateModel(
            name='RepairOfObject',
            fields=[
                ('creationact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.creationact')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.creationact',),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('genericevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.genericevent',),
        ),
        migrations.CreateModel(
            name='TransportationOfObject',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.RenameModel(
            old_name='ParticipationInBattle',
            new_name='ParticipationInEvent',
        ),
        migrations.RenameModel(
            old_name='UseInBattle',
            new_name='UtilisationInEvent',
        ),
        migrations.DeleteModel(
            name='Cannon',
        ),
    ]
