# Generated by Django 4.1.10 on 2023-07-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0009_arms_decorationofobject_festivity_giftgiving_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arms',
            options={'verbose_name': 'Arms', 'verbose_name_plural': 'Arms'},
        ),
        migrations.AlterModelOptions(
            name='assemblyofcompositeobject',
            options={'verbose_name': 'Assembly of Composite Object', 'verbose_name_plural': 'Assemblies of Composite Objects'},
        ),
        migrations.AlterModelOptions(
            name='communicateswith',
            options={'verbose_name': 'Communication With', 'verbose_name_plural': 'Communications With'},
        ),
        migrations.AlterModelOptions(
            name='creationoforganisation',
            options={'verbose_name': 'Creation of Organisations', 'verbose_name_plural': 'Creations of Organisations'},
        ),
        migrations.AlterModelOptions(
            name='decorationofobject',
            options={'verbose_name': 'Decoration of Object', 'verbose_name_plural': 'Decorations of Objects'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='festivity',
            options={'verbose_name': 'Festivity', 'verbose_name_plural': 'Festivities'},
        ),
        migrations.AlterModelOptions(
            name='groupofpersons',
            options={'verbose_name': 'Group of Persons', 'verbose_name_plural': 'Groups of Persons'},
        ),
        migrations.AlterModelOptions(
            name='participationinevent',
            options={'verbose_name': 'Participation in Event', 'verbose_name_plural': 'Participations in Events'},
        ),
        migrations.AlterModelOptions(
            name='transportationofobject',
            options={'verbose_name': 'Transportation of Object', 'verbose_name_plural': 'Transportations of Objects'},
        ),
        migrations.AlterModelOptions(
            name='utilisationinevent',
            options={'verbose_name': 'Utilisation in Event', 'verbose_name_plural': 'Utilisations in Events'},
        ),
    ]
