# Generated by Django 4.1.10 on 2023-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0012_factoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualobject',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='genericevent',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='genericstatement',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='groupofpersons',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='physicalobject',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True),
        ),
    ]
