# Generated by Django 4.1.10 on 2023-09-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0015_typology_roletype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArmourPiece',
            new_name='ArmourPart',
        ),
        migrations.RenameModel(
            old_name='DecorationOfObject',
            new_name='DecorationOfArmour',
        ),
        migrations.AlterModelOptions(
            name='acceptanceofstatement',
            options={'verbose_name': 'Befehlsannahme', 'verbose_name_plural': 'Befehlsannahmen'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Handlung', 'verbose_name_plural': 'Handlungen'},
        ),
        migrations.AlterModelOptions(
            name='armour',
            options={'verbose_name': 'Harnisch', 'verbose_name_plural': 'Harnische'},
        ),
        migrations.AlterModelOptions(
            name='armourassemblyact',
            options={'verbose_name': 'Zusammenstellung von Rüstungsteilen', 'verbose_name_plural': 'Zusammenstellungen von Rüstungsteilen'},
        ),
        migrations.AlterModelOptions(
            name='armourcreationact',
            options={'verbose_name': 'Herstellung eines Rüstungsteiles', 'verbose_name_plural': 'Herstellung von Rüstungsteilen'},
        ),
        migrations.AlterModelOptions(
            name='armourpart',
            options={'verbose_name': 'Rüstungsteil', 'verbose_name_plural': 'Rüstungsteile'},
        ),
        migrations.AlterModelOptions(
            name='arms',
            options={'verbose_name': 'Waffe', 'verbose_name_plural': 'Waffen'},
        ),
        migrations.AlterModelOptions(
            name='assignmenttorole',
            options={'verbose_name': 'Amtseinsetzung', 'verbose_name_plural': 'Amtseinsetzungen'},
        ),
        migrations.AlterModelOptions(
            name='battle',
            options={'verbose_name': 'Schlacht', 'verbose_name_plural': 'Schlachten'},
        ),
        migrations.AlterModelOptions(
            name='communicateswith',
            options={'verbose_name': 'Mitteilung', 'verbose_name_plural': 'Mitteilungen'},
        ),
        migrations.AlterModelOptions(
            name='creationact',
            options={'verbose_name': 'Herstellung', 'verbose_name_plural': 'Herstellungen'},
        ),
        migrations.AlterModelOptions(
            name='creationcommission',
            options={'verbose_name': 'Herstellungsauftrag', 'verbose_name_plural': 'Herstellungsaufträge'},
        ),
        migrations.AlterModelOptions(
            name='creationoforganisation',
            options={'verbose_name': 'Gründung einer Körperschaft', 'verbose_name_plural': 'Gründungen von Körperschaften'},
        ),
        migrations.AlterModelOptions(
            name='decorationofarmour',
            options={'verbose_name': 'Verzierung von Harnisch/Waffen', 'verbose_name_plural': 'Verzierungen von Harnisch/Waffen'},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name': 'Wahl', 'verbose_name_plural': 'Wahlen'},
        ),
        migrations.AlterModelOptions(
            name='festivity',
            options={'verbose_name': 'Fest', 'verbose_name_plural': 'Feste'},
        ),
        migrations.AlterModelOptions(
            name='genericstatement',
            options={'verbose_name': 'Do not use', 'verbose_name_plural': 'Definitely do not use'},
        ),
        migrations.AlterModelOptions(
            name='giftgiving',
            options={'verbose_name': 'Schenkung', 'verbose_name_plural': 'Schenkungen'},
        ),
        migrations.AlterModelOptions(
            name='militarycampaign',
            options={'verbose_name': 'Feldzug', 'verbose_name_plural': 'Feldzüge'},
        ),
        migrations.AlterModelOptions(
            name='naming',
            options={'verbose_name': 'Nennung', 'verbose_name_plural': 'Nennungen'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Befehle'},
        ),
        migrations.AlterModelOptions(
            name='organisationlocation',
            options={'verbose_name': 'Standort einer Körperschaft', 'verbose_name_plural': 'Standorte von Körperschaften'},
        ),
        migrations.AlterModelOptions(
            name='ownershiptransfer',
            options={'verbose_name': 'Besitztransfer', 'verbose_name_plural': 'Besitztransfere'},
        ),
        migrations.AlterModelOptions(
            name='participationinevent',
            options={'verbose_name': 'Teilnahme', 'verbose_name_plural': 'Teilnahmen'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Zahlung', 'verbose_name_plural': 'Zahlungen'},
        ),
        migrations.AlterModelOptions(
            name='performanceoftask',
            options={'verbose_name': 'Ausübung einer Tätigkeit', 'verbose_name_plural': 'Ausübungen von Tätigkeiten'},
        ),
        migrations.AlterModelOptions(
            name='performanceofwork',
            options={'verbose_name': 'Aufführung eines Werkes', 'verbose_name_plural': 'Aufführungen von Werken'},
        ),
        migrations.AlterModelOptions(
            name='removalfromrole',
            options={'verbose_name': 'Amtsenthebung', 'verbose_name_plural': 'Amtsenthebungen'},
        ),
        migrations.AlterModelOptions(
            name='roleoccupation',
            options={'verbose_name': 'Bekleidung eines Amtes', 'verbose_name_plural': 'Bekleidung von Ämtern'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tätigkeit', 'verbose_name_plural': 'Tätigkeiten'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Turnier', 'verbose_name_plural': 'Turniere'},
        ),
        migrations.AlterModelOptions(
            name='utilisationinevent',
            options={'verbose_name': 'Verwendung', 'verbose_name_plural': 'Verwendungen'},
        ),
        migrations.RemoveField(
            model_name='armour',
            name='armour_type',
        ),
        migrations.RemoveField(
            model_name='assignmenttorole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='removalfromrole',
            name='description',
        ),
    ]
