# Generated by Django 4.1.10 on 2023-09-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0018_transportationofarmour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Familienmitgliedschaft',
                'verbose_name_plural': 'Familienmitgliedschaften',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.RenameModel(
            old_name='AcceptanceOfStatement',
            new_name='AcceptanceOfOrder',
        ),
        migrations.AlterModelOptions(
            name='artisticwork',
            options={'verbose_name': 'Kunstwerk', 'verbose_name_plural': 'Kunstwerke'},
        ),
        migrations.AlterModelOptions(
            name='artworkcreationact',
            options={'verbose_name': 'Herstellung eines Kunstwerkes', 'verbose_name_plural': 'Herstellung von Kunstwerken'},
        ),
        migrations.AlterModelOptions(
            name='assemblyofcompositeobject',
            options={'verbose_name': 'Kombinierung mehrerer Objekte', 'verbose_name_plural': 'Kombinierungen mehrerer Objekte'},
        ),
        migrations.AlterModelOptions(
            name='authoring',
            options={'verbose_name': 'Autorenschaft', 'verbose_name_plural': 'Autorenschaften'},
        ),
        migrations.AlterModelOptions(
            name='birth',
            options={'verbose_name': 'Geburt', 'verbose_name_plural': 'Geburten'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Buch', 'verbose_name_plural': 'Bücher'},
        ),
        migrations.AlterModelOptions(
            name='compositeconceptualobject',
            options={'verbose_name': 'Zusammengesetztes konzeptionelles Objekt', 'verbose_name_plural': 'Zusammengesetzte konzeptionelle Objekte'},
        ),
        migrations.AlterModelOptions(
            name='compositephysicalobject',
            options={'verbose_name': 'Zusammengesetztes physisches Objekt', 'verbose_name_plural': 'Zusammengesetzte physische Objekte'},
        ),
        migrations.AlterModelOptions(
            name='compositetextualwork',
            options={'verbose_name': 'Sammelwerk', 'verbose_name_plural': 'Sammelwerke'},
        ),
        migrations.AlterModelOptions(
            name='conceptualobject',
            options={'verbose_name': 'Konzeptionelles Objekt', 'verbose_name_plural': 'Konzeptionelle Objekte'},
        ),
        migrations.AlterModelOptions(
            name='death',
            options={'verbose_name': 'Tod', 'verbose_name_plural': 'Tode'},
        ),
        migrations.AlterModelOptions(
            name='dedication',
            options={'verbose_name': 'Widmung', 'verbose_name_plural': 'Widmungen'},
        ),
        migrations.AlterModelOptions(
            name='dedicatorytext',
            options={'verbose_name': 'Werk mit Widmung', 'verbose_name_plural': 'Werke mit Widmungen'},
        ),
        migrations.AlterModelOptions(
            name='familialrelation',
            options={'verbose_name': 'Familiäre Verbindung', 'verbose_name_plural': 'Familiäre Verbindungen'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familie', 'verbose_name_plural': 'Familien'},
        ),
        migrations.AlterModelOptions(
            name='fictionalperson',
            options={'verbose_name': 'Fiktive Person', 'verbose_name_plural': 'Fiktive Personen'},
        ),
        migrations.AlterModelOptions(
            name='foundation',
            options={'verbose_name': 'Stiftung', 'verbose_name_plural': 'Stiftungen'},
        ),
        migrations.AlterModelOptions(
            name='genericevent',
            options={'verbose_name': 'Ereignis', 'verbose_name_plural': 'Ereignisse'},
        ),
        migrations.AlterModelOptions(
            name='groupofpersons',
            options={'verbose_name': 'Personengruppe', 'verbose_name_plural': 'Personengruppen'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='leaflet',
            options={'verbose_name': 'Flugblatt', 'verbose_name_plural': 'Flugblätter'},
        ),
        migrations.AlterModelOptions(
            name='manuscript',
            options={'verbose_name': 'Handschrift', 'verbose_name_plural': 'Handschriften'},
        ),
        migrations.AlterModelOptions(
            name='marriagebeginning',
            options={'verbose_name': 'Eheschließung', 'verbose_name_plural': 'Eheschließungen'},
        ),
        migrations.AlterModelOptions(
            name='marriageend',
            options={'verbose_name': 'Ende der Ehe', 'verbose_name_plural': 'Enden der Ehen'},
        ),
        migrations.AlterModelOptions(
            name='musicperformance',
            options={'verbose_name': 'Musikaufführung', 'verbose_name_plural': 'Musikaufführungen'},
        ),
        migrations.AlterModelOptions(
            name='musicwork',
            options={'verbose_name': 'Musikwerk', 'verbose_name_plural': 'Musikwerke'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Körperschaft', 'verbose_name_plural': 'Körperschaften'},
        ),
        migrations.AlterModelOptions(
            name='organisationlocation',
            options={'verbose_name': 'Ort einer Körperschaft', 'verbose_name_plural': 'Ort von Körperschaften'},
        ),
        migrations.AlterModelOptions(
            name='parentalrelation',
            options={'verbose_name': 'Elternschaft', 'verbose_name_plural': 'Elternschaften'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='physicalobject',
            options={'verbose_name': 'Physisches Objekt', 'verbose_name_plural': 'Physische Objekte'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Ort', 'verbose_name_plural': 'Orte'},
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'verbose_name': 'Gedicht', 'verbose_name_plural': 'Gedichte'},
        ),
        migrations.AlterModelOptions(
            name='preface',
            options={'verbose_name': 'Vorwort', 'verbose_name_plural': 'Vorworte'},
        ),
        migrations.AlterModelOptions(
            name='printedwork',
            options={'verbose_name': 'Druckwerk', 'verbose_name_plural': 'Druckwerke'},
        ),
        migrations.AlterModelOptions(
            name='printing',
            options={'verbose_name': 'Druck', 'verbose_name_plural': 'Drucke'},
        ),
        migrations.AlterModelOptions(
            name='redacting',
            options={'verbose_name': 'Bearbeitung', 'verbose_name_plural': 'Bearbeitungen'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Amt', 'verbose_name_plural': 'Ämter'},
        ),
        migrations.AlterModelOptions(
            name='roletype',
            options={'verbose_name': 'Amtstyp', 'verbose_name_plural': 'Amtstypen'},
        ),
        migrations.AlterModelOptions(
            name='secretarialact',
            options={'verbose_name': 'Schreibarbeit', 'verbose_name_plural': 'Schreibarbeiten'},
        ),
        migrations.AlterModelOptions(
            name='siblingrelation',
            options={'verbose_name': 'Geschwisterverhältnis', 'verbose_name_plural': 'Geschwisterverhältnisse'},
        ),
        migrations.AlterModelOptions(
            name='textualcreationact',
            options={'verbose_name': 'Textschöpfung', 'verbose_name_plural': 'Textschöpfungen'},
        ),
        migrations.AlterModelOptions(
            name='textualwork',
            options={'verbose_name': 'Text', 'verbose_name_plural': 'Texte'},
        ),
        migrations.AlterModelOptions(
            name='woodcut',
            options={'verbose_name': 'Holzschnitt', 'verbose_name_plural': 'Holzschnitte'},
        ),
        migrations.AlterField(
            model_name='gendering',
            name='gender',
            field=models.CharField(blank=True, choices=[('weiblich', 'Weiblich'), ('männlich', 'Männlich'), ('unbekannt', 'Unbekannt')], max_length=10, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='parentalrelation',
            name='parental_type',
            field=models.CharField(blank=True, choices=[('mutter', 'Mutter'), ('vater', 'Vater'), ('stiefmutter', 'Stiefmutter'), ('stiefvater', 'Stiefvater'), ('ziehmutter', 'Ziehmutter'), ('ziehvater', 'Ziehvater'), ('unbekannt', 'Unbekannt')], max_length=15, verbose_name='Art des Verhältnisses'),
        ),
        migrations.AlterField(
            model_name='siblingrelation',
            name='sibling_type',
            field=models.CharField(blank=True, choices=[('bruder', 'Bruder'), ('schwester', 'Schwester'), ('halbbruder', 'Halbbruder'), ('stiefbruder', 'Stiefbruder'), ('halbschwester', 'Halbschwester'), ('stiefschwester', 'Stiefschwester'), ('unbekannt', 'Unbekannt')], max_length=14, verbose_name='Art des Verhältnisses'),
        ),
    ]
