# Generated by Django 4.1.10 on 2023-09-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0020_armstype_alter_conceptualobject_internal_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arms',
            name='arms_type',
        ),
    ]
