# Generated by Django 4.1.10 on 2023-09-20 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0022_conceptualobject_alternative_schuh_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualobject',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='family',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='genericevent',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='genericstatement',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='groupofpersons',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='physicalobject',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='place',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='role',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='alternative_schuh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, size=None),
        ),
    ]
