# Generated by Django 4.1.10 on 2023-11-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0024_verschreibung_alter_naming_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Mitgliedschaft in einer Organisation/Gruppe',
                'verbose_name_plural': 'Mitgliedschaften in Organisationen/Gruppen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
