# Generated by Django 4.1.10 on 2023-11-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0025_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericRelationship',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Generic Relationship',
                'verbose_name_plural': 'Generic Relationships',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
