# Generated by Django 4.1.10 on 2023-11-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0026_genericrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionalPlace',
            fields=[
                ('conceptualobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.conceptualobject')),
            ],
            options={
                'verbose_name': 'Fiktive Person',
                'verbose_name_plural': 'Fiktive Personen',
            },
            bases=('apis_ontology.conceptualobject',),
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Generic Activity', 'verbose_name_plural': 'Generic Activities'},
        ),
        migrations.AlterModelOptions(
            name='fictionalperson',
            options={'verbose_name': 'Fiktiver Ort', 'verbose_name_plural': 'Fiktive Orte'},
        ),
        migrations.AlterModelOptions(
            name='genericstatement',
            options={'verbose_name': 'Generic Statement', 'verbose_name_plural': 'Generic Statements'},
        ),
    ]
