# Generated by Django 4.1.13 on 2023-12-04 11:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0001_initial'),
        ('apis_ontology', '0028_textualperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtOwed',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('amount', models.CharField(blank=True, max_length=255, verbose_name='Betrag')),
                ('currency', models.CharField(blank=True, max_length=255, verbose_name='Währung')),
                ('reason_for_debt', models.CharField(blank=True, max_length=1000, verbose_name='Grund für die Verschuldung')),
            ],
            options={
                'verbose_name': 'Schulden',
                'verbose_name_plural': 'Schulden',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TaxesAndIncome',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('created_by', models.CharField(blank=True, editable=False, max_length=300)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=300)),
                ('modified_when', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True, verbose_name='Interne Notizen')),
                ('schuh_index_id', models.CharField(blank=True, editable=False, max_length=500)),
                ('alternative_schuh_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, editable=False, size=None)),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Betrag')),
                ('currency', models.CharField(blank=True, max_length=255, verbose_name='Währung')),
            ],
            options={
                'verbose_name': 'Steuern und Einnahmen',
                'verbose_name_plural': 'Steuern und Einnahmen',
            },
            bases=('apis_entities.tempentityclass',),
        ),
    ]
