# Generated by Django 4.1.13 on 2023-12-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0030_alter_debtowed_amount_alter_debtowed_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepicitionOfPersonInArt',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Personendarstellung in Art',
                'verbose_name_plural': 'Personendarstellungen in Art',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextualCitationAllusion',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('part_of_alluding_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Part of citing text')),
                ('part_of_alluded_to_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Part of cited text')),
            ],
            options={
                'verbose_name': 'Textzitat/Textanspielung',
                'verbose_name_plural': 'Textzitaten/Textanspielungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
