# Generated by Django 4.1.13 on 2023-12-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0032_artworkhasadditionalname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depicitionofpersoninart',
            options={'verbose_name': 'Personendarstellung in Kunst', 'verbose_name_plural': 'Personendarstellungen in Kunst'},
        ),
    ]
