# Generated by Django 4.1.13 on 2024-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0033_alter_depicitionofpersoninart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='problem_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factoid',
            name='review_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='factoid',
            name='review_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factoid',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
