# Generated by Django 4.1.13 on 2024-09-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0034_factoid_problem_flagged_factoid_review_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('nature_of_dispute', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Art des Streits')),
            ],
            options={
                'verbose_name': 'Streit',
                'verbose_name_plural': 'Streite',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='RightsToPlace',
            fields=[
                ('conceptualobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.conceptualobject')),
            ],
            options={
                'verbose_name': 'Rechte am Ort',
                'verbose_name_plural': 'Rechte am Ort',
            },
            bases=('apis_ontology.conceptualobject',),
        ),
        migrations.CreateModel(
            name='RightsToPlaceType',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Rechte am Ortstyp',
                'verbose_name_plural': 'Rechte am Ortstypen',
            },
            bases=('apis_ontology.typology',),
        ),
    ]
