# Generated by Django 4.1.13 on 2024-09-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0035_dispute_rightstoplace_rightstoplacetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroupHasLocation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Aufenthaltsort',
                'verbose_name_plural': 'Aufenthaltsorte',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
