# Generated by Django 4.1.13 on 2024-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0036_persongrouphaslocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoid',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
