# Generated by Django 4.1.13 on 2024-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0041_genericstatement_certainty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualobject',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='conceptualobject',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='family',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='genericevent',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='genericevent',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='genericstatement',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='genericstatement',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='groupofpersons',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='groupofpersons',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='physicalobject',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='physicalobject',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='taxesandincome',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='taxesandincome',
            name='modified_by',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
    ]
