# Generated by Django 4.1.13 on 2024-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0043_reifiedrelation_personwithproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reifiedrelation',
            name='certainty',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reifiedrelation',
            name='certainty_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
