# Generated by Django 4.1.13 on 2024-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0044_alter_reifiedrelation_certainty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstatement',
            name='certainty',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='genericstatement',
            name='certainty_values',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reifiedrelation',
            name='certainty',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reifiedrelation',
            name='certainty_values',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
