# Generated by Django 4.1.13 on 2024-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apis_ontology', '0045_alter_genericstatement_certainty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField()),
                ('models_referenced', models.ManyToManyField(to='contenttypes.contenttype')),
            ],
        ),
    ]
