# Generated by Django 4.1.13 on 2025-03-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0046_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Taufe',
                'verbose_name_plural': 'Taufen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Begräbnis',
                'verbose_name_plural': 'Begräbnisse',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Ennoblement',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Veredelung',
                'verbose_name_plural': 'Veredlungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='EventCharacterisation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Charakterisierung von Ereignis',
                'verbose_name_plural': 'Charakterisierung von Ereignissen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='GrantingPermission',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Erlaubnis erteilen',
                'verbose_name_plural': 'Erlaubnis erteilen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('compositetextualwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.compositetextualwork')),
            ],
            options={
                'verbose_name': 'Inventar',
                'verbose_name_plural': 'Inventare',
            },
            bases=('apis_ontology.compositetextualwork',),
        ),
        migrations.CreateModel(
            name='InventoryCreation',
            fields=[
                ('textualcreationact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.textualcreationact')),
            ],
            options={
                'verbose_name': 'Erstellung von Inventar',
                'verbose_name_plural': 'Erstellungen von Inventare',
            },
            bases=('apis_ontology.textualcreationact',),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Einladung',
                'verbose_name_plural': 'Einladungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Reise',
                'verbose_name_plural': 'Reisen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='ObjectHasLocation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Objekt has Standort',
                'verbose_name_plural': 'Objekten haben Standorte',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='OrganisationIsPartOfOrganisation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'hat Unterorganisation',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextReferencesObject',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.AddField(
            model_name='naming',
            name='gen_name',
            field=models.CharField(blank=True, help_text='Namensteil zur Bezeichnung der Generationeninformation, z. B. „die Jungen“, „VIII“', max_length=200, null=True, verbose_name='Generationenname'),
        ),
        migrations.AddField(
            model_name='payment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('einmalig', 'einmalig'), ('wöchentlich', 'wöchentlich'), ('monatlich', 'monatlich'), ('jährlich', 'jährlich')], max_length=16, verbose_name='Häufigkeit der Zahlung'),
        ),
    ]
