# Generated by Django 4.1.13 on 2025-03-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0047_baptism_burial_ennoblement_eventcharacterisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epitaph',
            fields=[
                ('textualwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.textualwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.textualwork',),
        ),
    ]
