# Generated by Django 4.1.13 on 2025-04-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0048_epitaph'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Abschlusstyp',
                'verbose_name_plural': 'AmtsAbschlusstypen',
            },
            bases=('apis_ontology.typology',),
        ),
        migrations.CreateModel(
            name='EducationSubject',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Studienfach',
                'verbose_name_plural': 'Studienfachen',
            },
            bases=('apis_ontology.typology',),
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Studientyp',
                'verbose_name_plural': 'Studientypen',
            },
            bases=('apis_ontology.typology',),
        ),
        migrations.CreateModel(
            name='GenericEducation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Ausbildung',
                'verbose_name_plural': 'Ausbildungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Graduierung',
                'verbose_name_plural': 'Graduierungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Immatrikulation',
                'verbose_name_plural': 'Immatrikulationen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
