# Generated by Django 4.1.13 on 2025-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0050_unreconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualobject',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoid',
            name='contains_unreconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factoid',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericevent',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericstatement',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupofpersons',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalobject',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reifiedrelation',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxesandincome',
            name='reconcile_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
