# Generated by Django 4.1.13 on 2025-09-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0053_allowancetype_associationwithplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('familialrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.familialrelation')),
            ],
            options={
                'verbose_name': 'Vormundschaft',
                'verbose_name_plural': 'Vormundschaften',
            },
            bases=('apis_ontology.familialrelation',),
        ),
        migrations.CreateModel(
            name='IsCousinOf',
            fields=[
                ('familialrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.familialrelation')),
            ],
            options={
                'verbose_name': 'Ist Cousin von',
                'verbose_name_plural': 'Sind Cousins von',
            },
            bases=('apis_ontology.familialrelation',),
        ),
        migrations.CreateModel(
            name='IsUncleOf',
            fields=[
                ('familialrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.familialrelation')),
            ],
            options={
                'verbose_name': 'Ist Onkel/Tante von',
                'verbose_name_plural': 'Sind Onkel/Tanten von',
            },
            bases=('apis_ontology.familialrelation',),
        ),
        migrations.CreateModel(
            name='PersonReportsToPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'hat Vorgesetzten',
                'verbose_name_plural': 'hat Vorgesetzten',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='RoleOrOrganisationInServiceOfPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Amt/Organisation im Dienst von',
                'verbose_name_plural': 'Ämter/Organisationen im Dienst von',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='SiblingInLawRelation',
            fields=[
                ('familialrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.familialrelation')),
                ('in_law_type', models.CharField(blank=True, choices=[('schwager', 'Schwager'), ('schwagerin', 'Schwagerin')], max_length=14, verbose_name='Art des Verhältnisses')),
            ],
            options={
                'verbose_name': 'Schwager Verhältnis',
                'verbose_name_plural': 'Schwager Verhältnisse',
            },
            bases=('apis_ontology.familialrelation',),
        ),
    ]
