# Generated by Django 4.1.13 on 2025-09-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0054_guardianship_iscousinof_isuncleof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownStatementType',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Unknown Statement Type',
                'verbose_name_plural': 'Unknown Statement Type',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
