# Generated by Django 4.1.13 on 2025-09-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0055_unknownstatementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownstatementtype',
            name='autosuggested_statement_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unknownstatementtype',
            name='suggested_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
