# Generated by Django 4.1.13 on 2025-10-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0056_unknownstatementtype_autosuggested_statement_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInLawRelation',
            fields=[
                ('familialrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.familialrelation')),
                ('parent_in_law_type', models.CharField(blank=True, choices=[('schwiegermutter', 'Schwiegermutter'), ('schwiegervater', 'Schwiegervater')], max_length=16, verbose_name='Art des Verhältnisses')),
            ],
            options={
                'verbose_name': 'Schwiegerelternverhältnis',
                'verbose_name_plural': 'Schwiegerelternverhältnisse',
            },
            bases=('apis_ontology.familialrelation',),
        ),
    ]
