# Generated by Django 4.1.13 on 2025-10-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0057_parentinlawrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Erbe',
                'verbose_name_plural': 'Erbe',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
