# Generated by Django 4.1.13 on 2025-10-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0058_heir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApologyForNonAttendance',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Bitte um Entschuldigung für Abwesenheit',
                'verbose_name_plural': 'Bitten um Entschuldigung für Abwesenheit',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='DeliveryOfText',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Überbringung von Text',
                'verbose_name_plural': 'Überbringungen von Texten',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='WitnessToSigning',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Unterfertigungszeuge',
                'verbose_name_plural': 'Unterfertigungszeuge',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
