# Generated by Django 4.1.13 on 2025-12-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0059_apologyfornonattendance_deliveryoftext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionOfTextToManuscript',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Hinzufügung von Text zum Manuskript',
                'verbose_name_plural': 'Hinzufügung von Text zum Manuskript',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextAnnounces',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Text kündigt an',
                'verbose_name_plural': 'Text kündigt an',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextAsksForPatronage',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Text bittet um Unterstützung',
                'verbose_name_plural': 'Text bittet um Unterstützung',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextExpressesLamentation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Text drückt Klage aus',
                'verbose_name_plural': 'Text drückt Klage aus',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextExpressesThanks',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Text drückt Dankbarkeit aus',
                'verbose_name_plural': 'Text drückt Dankbarkeit aus',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextMakesNegativeStatementAboutPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('statement_description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung der Aussage')),
            ],
            options={
                'verbose_name': 'Text macht eine negative Aussage über die Person',
                'verbose_name_plural': 'Texte machen negative Aussage über Personen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextMakesPositiveStatementAboutPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('statement_description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung der Aussage')),
            ],
            options={
                'verbose_name': 'Text macht eine positive Aussage über die Person',
                'verbose_name_plural': 'Texte machen positive Aussage über Personen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='TextReferencesEvent',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Text bezieht sich auf ein Ereignis',
                'verbose_name_plural': 'Text bezieht sich auf ein Ereignis',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
