# Generated by Django 4.1.13 on 2026-01-23 09:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0001_initial'),
        ('apis_ontology', '0060_additionoftexttomanuscript_textannounces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndeterminatePhysicalObject',
            fields=[
                ('physicalobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.physicalobject')),
            ],
            options={
                'verbose_name': 'indeterminate physical object',
                'verbose_name_plural': 'unbestimmte physische Objekte',
            },
            bases=('apis_ontology.physicalobject',),
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('created_by', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('modified_when', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True, verbose_name='Interne Notizen')),
                ('schuh_index_id', models.CharField(blank=True, editable=False, max_length=500)),
                ('alternative_schuh_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, editable=False, size=None)),
                ('reconcile_text', models.TextField(blank=True, default='', null=True)),
                ('amount_per_annum', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Gehälter',
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('created_by', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('modified_when', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal searchable text, for disambiguation. Store information as statements!', null=True, verbose_name='Interne Notizen')),
                ('schuh_index_id', models.CharField(blank=True, editable=False, max_length=500)),
                ('alternative_schuh_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, editable=False, max_length=500), default=list, editable=False, size=None)),
                ('reconcile_text', models.TextField(blank=True, default='', null=True)),
                ('amount_per_annum', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Gehälter',
            },
            bases=('apis_entities.tempentityclass',),
        ),
    ]
