# Generated by Django 4.1.13 on 2026-01-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0061_indeterminatephysicalobject_pension_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pension',
            options={'verbose_name': 'Renten'},
        ),
    ]
