# Generated by Django 4.1.13 on 2026-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0062_alter_pension_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='factoid_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
