# Generated by Django 4.1.13 on 2026-02-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0063_factoid_factoid_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeTextualWorkIsComposedOf',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Sammelwerk ist zusammengestellt aus',
                'verbose_name_plural': 'Sammelwerk ist zusammengestellt aus',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.AlterField(
            model_name='factoid',
            name='factoid_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Full Factoid Text'),
        ),
    ]
