# Generated by Django 4.1.13 on 2026-02-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0064_compositetextualworkiscomposedof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editing',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Herausgeberschaft',
                'verbose_name_plural': 'Herausgeberschaften',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
            },
            bases=('apis_ontology.typology',),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Übersetzung',
                'verbose_name_plural': 'Übersetzungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.AddField(
            model_name='person',
            name='person_outside_timeframe',
            field=models.BooleanField(default=False, help_text='Person lived well outside the timeframe of the project and should not be part of, e.g. social/relational networks. E.g. Aristotle'),
        ),
    ]
