# Generated by Django 4.1.13 on 2026-03-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0065_editing_language_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentOfEndowment',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('monetary_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Errichtung einer Stiftung',
                'verbose_name_plural': 'Errichtungen von Stiftungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_outside_timeframe',
            field=models.BooleanField(blank=True, default=False, help_text='Person lived well outside the timeframe of the project and should not be part of, e.g. social/relational networks. E.g. Aristotle', null=True),
        ),
    ]
