# Generated by Django 4.1.13 on 2026-03-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0066_establishmentofendowment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextRefersToPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('statement_description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung der Aussage')),
            ],
            options={
                'verbose_name': 'Text macht eine Aussage über die Person',
                'verbose_name_plural': 'Texte machen Aussage über Personen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
