# Generated by Django 4.1.13 on 2026-05-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0067_textreferstoperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreconciled',
            name='is_in_factoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis_ontology.factoid'),
        ),
    ]
