# Generated by Django 4.1.13 on 2026-05-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0068_unreconciled_is_in_factoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionOfIntention',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Äußerung eines Vorhabens',
                'verbose_name_plural': 'Äußerungen von Vorhaben',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
