# Generated by Django 4.1.13 on 2026-05-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0069_expressionofintention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprisonment',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Gefangenschaft',
                'verbose_name_plural': 'Gefangenschaften',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='RecommendationOfAction',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Empfehlung einer Handlung',
                'verbose_name_plural': 'Empfehlungen von Handlungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='RecommendationOfPerson',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Empfehlung von einer Person',
                'verbose_name_plural': 'Empfehlungen von Personen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Weigerung',
                'verbose_name_plural': 'Weigerungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
