# Generated by Django 4.1.13 on 2026-05-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0071_alter_payment_amount_alter_payment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OathType',
            fields=[
                ('typology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.typology')),
            ],
            options={
                'verbose_name': 'Oath Type',
                'verbose_name_plural': 'Oath Types',
            },
            bases=('apis_ontology.typology',),
        ),
        migrations.CreateModel(
            name='SwearingOfOath',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Swearing of Oath',
                'verbose_name_plural': 'Swearing of Oaths',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='UnstructuredStatement',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'UnstructuredStatement',
                'verbose_name_plural': 'UnstructuredStatement',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
