# Generated by Django 4.1.13 on 2026-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0072_oathtype_swearingofoath_unstructuredstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='final_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
