# Generated by Django 4.1.13 on 2026-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0073_factoid_final_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericstatement',
            name='statement_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
