# Generated by Django 4.1.13 on 2026-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0074_genericstatement_statement_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoid',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
