# Generated by Django 4.1.13 on 2026-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0075_factoid_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('einmalig', 'einmalig'), ('wöchentlich', 'wöchentlich'), ('monatlich', 'monatlich'), ('jährlich', 'jährlich')], default='einmalig', max_length=16, verbose_name='Häufigkeit der Zahlung'),
        ),
    ]
