# Generated by Django 4.1.13 on 2026-06-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0076_alter_payment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalInstrument',
            fields=[
                ('physicalobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.physicalobject')),
            ],
            options={
                'verbose_name': 'Musikinstrument',
                'verbose_name_plural': 'Musikinstrumente',
            },
            bases=('apis_ontology.physicalobject',),
        ),
    ]
