# Generated by Django 4.1.13 on 2026-06-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0077_musicalinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceFromEvent',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Abwesenheit bei einem Ereignis',
                'verbose_name_plural': 'Abwesenheiten von Ereignissen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='AbsenceFromPlace',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Abwesenheit an einem Ort',
                'verbose_name_plural': 'Abwesenheiten von Orten',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='NegativeOrder',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Negative Befehl',
                'verbose_name_plural': 'Negative Befehlen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='Prohibition',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Verbot',
                'verbose_name_plural': 'Verbote',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.AlterModelOptions(
            name='ennoblement',
            options={'verbose_name': 'Nobilitierung', 'verbose_name_plural': 'Nobilitierungen'},
        ),
    ]
