# Generated by Django 4.1.13 on 2026-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0078_absencefromevent_absencefromplace_negativeorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('einmalig', 'einmalig'), ('wöchentlich', 'wöchentlich'), ('monatlich', 'monatlich'), ('jährlich', 'jährlich'), ('regular (unknown frequency)', 'regular (unknown frequency)')], default='einmalig', max_length=30, verbose_name='Häufigkeit der Zahlung'),
        ),
    ]
