# Generated by Django 4.1.13 on 2026-07-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0079_alter_payment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancePerformance',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Tanzaufführung',
                'verbose_name_plural': 'Tanzaufführungen',
            },
            bases=('apis_ontology.genericstatement',),
        ),
        migrations.CreateModel(
            name='OrderedNotCarriedOut',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Befehl erteilt, aber nicht ausgeführt',
                'verbose_name_plural': 'Befehl erteilt, aber nicht ausgeführt',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
