# Generated by Django 4.1.13 on 2026-09-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0080_danceperformance_orderednotcarriedout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theft',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Diebstahl',
                'verbose_name_plural': 'Diebstähle',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
