# Generated by Django 4.1.13 on 2026-09-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0081_theft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkBasedOnArtwork',
            fields=[
                ('genericstatement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.genericstatement')),
            ],
            options={
                'verbose_name': 'Kunstwerk basierend auf Kunstwerk',
                'verbose_name_plural': 'Kunstwerk basierend auf Kunstwerk',
            },
            bases=('apis_ontology.genericstatement',),
        ),
    ]
